### ISSUE TITLE
not an issue - question regarding watching bitcoin addresses

### ISSUE THREAD

**Issue by johndpope** [kishikawakatsumi/BitcoinKit#12]
somebody built a service to watch bitcoin addresses - 
it leverages WebSockets from (url: URL(string: "wss://ws.blockchain.info/inv 

https://github.com/johndpope/bitwake/blob/develop/BitWake/BitcoinBlockchain.swift

is it possible with all technology onboard this app to query this from blockchain?

**Comment by kishikawakatsumi** [comment]
@johndpope Yes. This library can download blockchain from node.

**Comment by johndpope** [comment]
I imagine the chain would have to be > 500gb ? does it sync back to genesis block? or did I miss something?

**Comment by kishikawakatsumi** [comment]
@johndpope Yes, so a wallet which is called SPV wallet download only block headers, not entire blocks. That is suitable for a mobile app. This library also behaves that by default. I meant, "if you'd like to" sync full blockchain, you can.
