### ISSUE TITLE
enhancement - wallet - surface visibility of  mainnet / testnet 

### ISSUE THREAD

**Issue by johndpope** [kishikawakatsumi/BitcoinKit#16]
public static let mainnet: Network = Mainnet()
    public static let testnet: Network = Testnet()

or show maybe just some way to control this flow from app developer without modifying Bitcoinkit.

**Comment by kishikawakatsumi** [comment]
@johndpope What do you mean? `HDWallet` accepts network type (mainnet or testnet) by a parameter. For `Wallet`, network type is determined by the key which is corresponded to it. You don't need to modify the library code.

**Comment by johndpope** [comment]
Closing this.

 I have use case where it just needs to be clear to end user which network they’re on. It’s doesnt need to switch but just be visible in wallet.

**Comment by johndpope** [comment]
I think when I saw this code - it would be desirable to be able to change the bitcoinkit network without having to recompile code. as in - using it as a pod. 

eg. want to be able to hot swap which network from appdelegate.

**Comment by kishikawakatsumi** [comment]
I don't understand what you are saying. I think that it can be achieved depending on how you implement the application. What kind of support is needed on the library side?

**Comment by johndpope** [comment]
looking at the bread library - they have some ruby scripts to toggle flags from at project level - this might be a better way to switch things moving forward. will close this. 
to be clear - the idea that this codebase can be imported by a cocoapod as a dependency as a kit - the developer who consumes library will need some way to override the init call to use either the testnet or mainnet. at the moment that code lives inside bitcoinkit.

**Comment by kishikawakatsumi** [comment]
You probably misunderstood the API. You can change the behavior just passing parameters in code. Do not need to override or else
