### ISSUE TITLE
enhancement - bitcoin cash address (BCH) Network.swift

### ISSUE THREAD

**Issue by johndpope** [kishikawakatsumi/BitcoinKit#18]
Currently we have 
https://gist.github.com/johndpope/ff350a12a8da933175e76d6c2d492c52
would be a milestone to be huge milestone to be able to support BCH. 

can use this 
https://www.reddit.com/r/btc/comments/6nqw7v/in_case_you_were_wondering_this_is_the_list_of/?st=jddb4nuu&sh=cc635f30

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/chainparams.cpp

**Comment by kishikawakatsumi** [comment]
Yes, supporting other coins is on the roadmap.
