### ISSUE TITLE
Problem installing via Carthage

### ISSUE THREAD

**Issue by Yaro812** [kishikawakatsumi/BitcoinKit#39]
After installing with Carthage i receive an error `Missing required module secp256k1`

There are no problems installing the framework with CocoaPods, though.

**Comment by fengxuelei** [comment]
I also encountered this problem

**Comment by kishikawakatsumi** [comment]
@Yaro812 @fengxuelei Can you please provide a reproducible sample project?

**Comment by Yaro812** [comment]
Just a new iOS single view project with Cartfile with only BitcoinKit dependency would go to reproduce the problem

**Comment by kishikawakatsumi** [comment]
@Yaro812 I cannot reproduce the issue in my environment. To resolve the issue, I need more details to reproduce it.

**Comment by kishikawakatsumi** [comment]
@Yaro812 I have never seen the error.  Please provide the following information.

- What version of Carthage do you use?
- What version of Xcode do you use?
- Copy & paste a full console log and build log after `carthage update --platform iOS`

**Comment by Yaro812** [comment]
@kishikawakatsumi interesting
**Carthage** 
version is `0.29.0`

**Xcode** 
`Version 9.2 (9C40b)`

**Console log:**
`carthage update --platform iOS
*** Fetching BitcoinKit
*** Checking out BitcoinKit at "v0.1.2"
*** xcodebuild output can be found in /var/folders/nq/bp7qw41d3n1ffsh_s6_wcnl00000gn/T/carthage-xcodebuild.dVDWbb.log
*** Downloading BitcoinKit.framework binary at "v0.1.2"`

**Full build log:**
`xcodebuild build
=== BUILD TARGET TestBitcoinKit OF PROJECT TestBitcoinKit WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Write auxiliary files
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Script-6DCBE7D62063B2B7003631DE.sh
chmod 0755 /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Script-6DCBE7D62063B2B7003631DE.sh
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-all-non-framework-target-headers.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-generated-files.hmap
/bin/mkdir -p /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit.LinkFileList
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/swift-overrides.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-all-target-headers.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-own-target-headers.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-project-headers.hmap
write-file /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit-OutputFileMap.json

Create product structure
/bin/mkdir -p /Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos/TestBitcoinKit.app

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/thorax/Desktop/TestBitcoinKit
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/thorax/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/thorax/.rvm/gems/ruby-2.4.0/bin:/Users/thorax/.rvm/gems/ruby-2.4.0@global/bin:/Users/thorax/.rvm/rubies/ruby-2.4.0/bin:/Users/thorax/.rvm/bin:/Users/thorax/Library/Android/sdk/tools:/Users/thorax/Library/Android/sdk/platform-tools"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name TestBitcoinKit -O -whole-module-optimization -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -target arm64-apple-ios11.2 -g -Xfrontend -serialize-debugging-options -embed-bitcode-marker -Xfrontend -report-errors-to-debugger -swift-version 4 -I /Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos -F /Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos -F /Users/thorax/Desktop/TestBitcoinKit/Carthage/Build/iOS -c -num-threads 8 /Users/thorax/Desktop/TestBitcoinKit/TestBitcoinKit/ViewController.swift /Users/thorax/Desktop/TestBitcoinKit/TestBitcoinKit/AppDelegate.swift -output-file-map /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit.swiftmodule -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-generated-files.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-own-target-headers.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-all-target-headers.hmap -Xcc -iquote -Xcc /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-project-headers.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos/include -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/DerivedSources/arm64 -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit-Swift.h -Xcc -working-directory/Users/thorax/Desktop/TestBitcoinKit

CompileSwift normal arm64
    cd /Users/thorax/Desktop/TestBitcoinKit
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/thorax/Desktop/TestBitcoinKit/TestBitcoinKit/ViewController.swift /Users/thorax/Desktop/TestBitcoinKit/TestBitcoinKit/AppDelegate.swift -target arm64-apple-ios11.2 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -I /Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos -F /Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos -F /Users/thorax/Desktop/TestBitcoinKit/Carthage/Build/iOS -g -swift-version 4 -serialize-debugging-options -report-errors-to-debugger -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-generated-files.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-own-target-headers.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-all-target-headers.hmap -Xcc -iquote -Xcc /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/TestBitcoinKit-project-headers.hmap -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/Release-iphoneos/include -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/DerivedSources/arm64 -Xcc -I/Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/DerivedSources -Xcc -working-directory/Users/thorax/Desktop/TestBitcoinKit -emit-module-doc-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit.swiftdoc -serialize-diagnostics-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/ViewController.dia -O -module-name TestBitcoinKit -emit-module-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit.swiftmodule -emit-objc-header-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/TestBitcoinKit-Swift.h -emit-dependencies-path /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/ViewController.d -num-threads 8 -o /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/ViewController.o -o /Users/thorax/Desktop/TestBitcoinKit/build/TestBitcoinKit.build/Release-iphoneos/TestBitcoinKit.build/Objects-normal/arm64/AppDelegate.o -embed-bitcode-marker
/Users/thorax/Desktop/TestBitcoinKit/TestBitcoinKit/ViewController.swift:10:8: error: missing required module 'secp256k1'
import BitcoinKit
       ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

**Comment by fengxuelei** [comment]
How to solve this problem in carthage？Still need to use CocoaPods？

**Comment by J-Liu** [comment]
`	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
`
It is my first time to try iOS code, what should I do?
