### ISSUE TITLE
carthage update --platform iOS --no-use-binaries trips up - 

### ISSUE THREAD

**Issue by johndpope** [kishikawakatsumi/BitcoinKit#4]
<img width="1086" alt="screen shot 2018-02-05 at 3 50 04 pm" src="https://user-images.githubusercontent.com/289994/35828066-41a333bc-0a8c-11e8-8a4f-114aa3850d88.png">

**Comment by johndpope** [comment]
https://github.com/Carthage/Carthage/issues/135

tried running this - but no joy.
git submodule update --init --recursive

**Comment by kishikawakatsumi** [comment]
@johndpope I forgot to check fresh environment, sorry. This issue will be fixed by #5 . I will merge it after checking some edge cases. In the meantime, you can "carthage" branch.


```
github "kishikawakatsumi/BitcoinKit" "carthage"
```

Thanks for reporting!
