### ISSUE TITLE
autogen.sh: line 3: autoreconf: command not found

### ISSUE THREAD

**Issue by fengxuelei** [kishikawakatsumi/BitcoinKit#42]
Installing BitcoinKit (0.1.2)
[!] /bin/bash -c
set -e
sh setup/build_libraries.sh

++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz
+ trap '{ cd - ; rm -rf /var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz; exit 255; }' SIGINT
+ cd /var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz
+ TARGETDIR_IPHONEOS=/var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz/.build/iphoneos
+ mkdir -p /var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz/.build/iphonesimulator
+ mkdir -p /var/folders/kc/g4hgtv816bq6w5n211rcvkgr0000gn/T/tmp.uevG4VYz/.build/iphonesimulator
+ cd src
+ ./autogen.sh
./autogen.sh: line 3: autoreconf: command not found

**Comment by fengxuelei** [comment]
Cocoapod import above mistakes

**Comment by kishikawakatsumi** [comment]
BitcoinKit builds secp256k1 and OpenSSL itself for security reasons. They requires autoconf and automake. Please install them. `brew install autoconf automake`

**Comment by QA411** [comment]
I have the same problem. pls help me
