### ISSUE TITLE
[!] Unable to find a specification for `BitcoinKit`

### ISSUE THREAD

**Issue by izalisky** [kishikawakatsumi/BitcoinKit#46]
[!] Unable to find a specification for `BitcoinKit`
<img width="368" alt="screen shot 2018-04-07 at 1 18 54 am" src="https://user-images.githubusercontent.com/3285187/38446613-b014c726-3a01-11e8-90b9-dcd048543a92.png">

**Comment by itali43** [comment]
Also got this, after a fair amount of troubleshooting.  Using 10.0 as my platform (iOS).
