### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by MaoxinCao** [kishikawakatsumi/BitcoinKit#55]
![111](https://user-images.githubusercontent.com/16041150/41223898-a81e79de-6d9d-11e8-87ad-4fa789869855.png)

Hi, Can you help me see this problem?

**Comment by Gensun** [comment]
@MaoxinCao 有思路了吗？

**Comment by Gensun** [comment]
update is ok

**Comment by MaoxinCao** [comment]
@Gensun 都不行...

**Comment by Gensun** [comment]
@MaoxinCao Carthage update

**Comment by AlleniCode** [comment]
@MaoxinCao 解决了吗？
![wechatimg1](https://user-images.githubusercontent.com/8855341/42011746-73e3843e-7ac7-11e8-9b44-2d6c25ff72cd.jpeg)
