### ISSUE TITLE
HDWallet.swift file not copied to the project

### ISSUE THREAD

**Issue by bogdan-razvan** [kishikawakatsumi/BitcoinKit#60]
After installing BitcointKit via cocoapods the file `HDWallet` is copied along with the pod's files for some reason. If copied from the repository directly into the project everything works fine. 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/24735120/41914380-95ad6584-795b-11e8-8fa3-65ec84ab64e7.png">

**Comment by kishikawakatsumi** [comment]
@bogdan-razvan HDWallet.swift is not included in `v0.12`. This is still work in progress. But you'd like to use it, use `master` branch.
