### ISSUE TITLE
HDPrivateKey derived bug, privateKey mast be 32 bytes

### ISSUE THREAD

**Issue by Jax1993** [kishikawakatsumi/BitcoinKit#73]
This bug comes up occasionally.
I solved the bug by:

    //in HDPrivateKey.swift
    extension HDPrivateKey {
    func bug_fix_ensure_32_bytes(data: Data) -> Data {
        let length = data.count
        if length >= 32 {
            return data
        }
        var dataFixed = Data()
        var int0 = UInt8(0)
        let data_0: Data = Data(buffer: UnsafeBufferPointer(start: &int0, count: 1))
        for i in 0..<32-length {
            dataFixed.append(data_0)
        }
        dataFixed.append(data)
        return dataFixed
    }
    }

    var privateKeyFixed = bug_fix_ensure_32_bytes(data: keys[0])
    var chainCodeFixed = bug_fix_ensure_32_bytes(data: keys[1])

**Comment by usatie** [comment]
@Jax1993 Hi!
Is this the same issue as #47 ?
If so, please see the issue first, and give us the specific case that reproduce this error please.

**Comment by SwenVanZanten** [comment]
I have a reproduction for this.

```swift
func testDeriveProblem() {
    let seed = Data(hex: "f27fd395d30d00f1c11b7551a93961ca41c0a78bce21e9a618e83a99cf74aec159139ef3ef078bc0038557b7cb689933d0806ce33571df78bc4397e7f9976ff2")!
    
    let key = try? HDPrivateKey(seed: seed, network: .mainnet)
        .derived(at: 44, hardened: true)
        .derived(at: 0, hardened: true)
        .derived(at: 0, hardened: true)
        .derived(at: 1)
        .derived(at: 19)
    
    print(key?.raw)
    print(key?.privateKey().description)
    print(key?.privateKey().publicKey().description)
    print(key?.privateKey().publicKey().toLegacy())
}
```

Result:
```
Optional(31 bytes)
Optional("5KfCepCbKNsNxNUZHjepoM5i3RnLyfkNZvQYZaSd9dVt6cDPzLz")
Optional("02a712f894d58baef44e4fbbc26ed6ca89487db1f17e944f9b45ca2ae666e99d72")
Optional(1DPUysR46jraybTwP3PfSbcBENeLScLxx)
```

This will give you 31 bytes.
Change the last derive to 20 or 18 and you'll get 32 bytes.

**Comment by SwenVanZanten** [comment]
> This bug comes up occasionally.
> I solved the bug by:
> 
> ```
> //in HDPrivateKey.swift
> extension HDPrivateKey {
> func bug_fix_ensure_32_bytes(data: Data) -> Data {
>     let length = data.count
>     if length >= 32 {
>         return data
>     }
>     var dataFixed = Data()
>     var int0 = UInt8(0)
>     let data_0: Data = Data(buffer: UnsafeBufferPointer(start: &int0, count: 1))
>     for i in 0..<32-length {
>         dataFixed.append(data_0)
>     }
>     dataFixed.append(data)
>     return dataFixed
> }
> }
> 
> var privateKeyFixed = bug_fix_ensure_32_bytes(data: keys[0])
> var chainCodeFixed = bug_fix_ensure_32_bytes(data: keys[1])
> ```

This fixes the problem
